version: '3.8'
services:
  app:
    container_name: app
    build: .
    command: sh -c "cd src && node load && npm start"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    expose:
      - 3000

  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    expose:
      - 5432

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    expose:
      - 27017
  # dynamodb:
  #   image: amazon/dynamodb-local
  #   container_name: dynamodb
  #   hostname: dynamodb
  #   restart: always
  #   volumes:
  #     - ./dynamodb-data:/home/dynamodblocal/data
  #   ports:
  #     - 8000:8000
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  # networks:
  #   postgres:
  #     name: postgres
